service: api-guides-printing

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

custom:
  webpack:
    includeModules:
      forceExclude:
        - aws-sdk
        - typescript
    webpackConfig: ./webpack.config.js

provider:
  name: aws
  stage: dev
  region: eu-west-1
  runtime: nodejs16.x
  memorySize: 512
  timeout: 10
  endpointType: REGIONAL
  environment:
    SHIPMENTS_FOR_PRINTING_TABLE: 'guidesForPrinting'
    INDEX_SHIPMENTS_FOR_PRINTING_CREATED_AT: 'createdAt-index'
    CLIENTS_TABLE_NAME: 'clients'
    BUCKET_S3_NAME: 'orion-services-bucket'
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
        - 's3:PutObject'
        - 's3:GetObject'
        - 's3:DeleteObject'
      Resource:
        - arn:aws:dynamodb:eu-west-1:*:table/orders
        - arn:aws:dynamodb:eu-west-1:*:table/clients
        - arn:aws:dynamodb:eu-west-1:*:table/cities
        - arn:aws:dynamodb:eu-west-1:*:table/destinyTypes
        - arn:aws:dynamodb:eu-west-1:*:table/subsidiaries
        - arn:aws:dynamodb:eu-west-1:*:table/shipments
        - arn:aws:dynamodb:eu-west-1:*:table/settings
        - arn:aws:dynamodb:eu-west-1:*:table/clientQuotes
        - arn:aws:dynamodb:eu-west-1:*:table/guidesForPrinting
        - arn:aws:dynamodb:eu-west-1:*:table/coverageMatrix
        - 'arn:aws:dynamodb:eu-west-1:*:table/orders/index/*'
        - 'arn:aws:dynamodb:eu-west-1:*:table/clients/index/*'
        - 'arn:aws:dynamodb:eu-west-1:*:table/cities/index/*'
        - 'arn:aws:dynamodb:eu-west-1:*:table/destinyTypes/index/*'
        - 'arn:aws:dynamodb:eu-west-1:*:table/subsidiaries/index/*'
        - 'arn:aws:dynamodb:eu-west-1:*:table/shipments/index/*'
        - 'arn:aws:dynamodb:eu-west-1:*:table/settings/index/*'
        - 'arn:aws:dynamodb:eu-west-1:*:table/clientQuotes/index/*'
        - 'arn:aws:dynamodb:eu-west-1:*:table/guidesForPrinting/index/*'
        - 'arn:aws:dynamodb:eu-west-1:*:table/coverageMatrix/index/*'
        - 'arn:aws:s3:::orion-services-bucket/*'

resources:
  Resources:
    OrionServicesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: orion-services-bucket
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
              AllowedOrigins:
                - '*'
    GuidesForPrintingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: guidesForPrinting
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
          - AttributeName: createdAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: createdAt-index
            KeySchema:
              - AttributeName: createdAt
                KeyType: HASH
            Projection:
              ProjectionType: ALL

outputs:
  OrionServicesBucket:
    Description: Bucket Created using this template.
    Value: !Ref OrionServicesBucket
  GuidesForPrintingTable:
    Description: Table Created using this template.
    Value: !Ref GuidesForPrintingTable

functions:
  main:
    handler: src/main.handler
    events:
      - http:
          method: ANY
          path: /api-guides-printing
          cors:
            origins:
              - '*'
      - http:
          method: ANY
          cors:
            origins:
              - '*'
          path: '{proxy+}'
